# Deployment - api Node - conversão temperatura
apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversao-temperatura
spec:
  selector:
    matchLabels:
      app: conversao-temperatura
  template:
    metadata:
      labels:
        app: conversao-temperatura
    spec:
      containers:
      - name: conversao-temperatura
        image: luizbotelho90/conversao-temperatura:v2
        ports: 
          - containerPort: 8081
---
apiVersion: v1 
kind: Service 
metadata: 
  name: conversao-temperatura
spec:
  selector:
    app: conversao-temperatura
  ports: 
  - port: 81
    targetPort: 8081
    nodePort: 31000
  type: NodePort
